server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://yi-sao.com:3306/demo-jpa
    username: demo-jpa
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace