server:
  port: 8977

#  ?????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://yi-sao.com:3306/search?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: yisao@123
      initial-size: 50
      max-active: 100
      min-idle: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  mail:
    host: smtp.qq.com
    port: 587
    username: 1786331791@qq.com
    password: roenhdjoipanifea
    from: 1786331791@qq.com
    properties:
      mail:
        stmp:
          ssl:
            enable: true
